
IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'SQL_Practice')
	DROP DATABASE SQL_Practice
GO

CREATE DATABASE SQL_Practice;
GO
USE SQL_Practice;
GO

IF NOT EXISTS (SELECT * FROM SYS.databases WHERE name = 'SQL_Practice')
BEGIN
	CREATE DATABASE SQL_Practice
END;
GO


CREATE TABLE Customers (
    CUSTOMERID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(64) NOT NULL,
    PHONE BIGINT NOT NULL        
    )
GO


CREATE TABLE Orders (
    ORDERID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMERID INT REFERENCES CUSTOMERS(CUSTOMERID)       
    )
GO



CREATE TABLE Items (
    ITEMID INT PRIMARY KEY IDENTITY(1,1),
    PRICE INT NOT NULL,
    ITEMNAME VARCHAR(100),
    DESCRIPTION VARCHAR(500)
    )
GO



CREATE TABLE OrderItems (
    ORDERITEMID INT PRIMARY KEY IDENTITY(1,1),
    ORDERID INT REFERENCES ORDERS(ORDERID),
    ITEMID INT REFERENCES ITEMS(ITEMID),
    QUANTITY INT NOT NULL
    )
GO

