DELETE FROM OrderItems
DBCC CHECKIDENT(OrderItems, RESEED, 0)
DELETE FROM Orders
DBCC CHECKIDENT(Orders, RESEED, 0)
DELETE FROM Items
DBCC CHECKIDENT(Items, RESEED, 0)
DELETE FROM Customers
DBCC CHECKIDENT(Customers, RESEED, 0)

--INSERT CUSTOMERS
INSERT INTO Customers (NAME, PHONE) VALUES ('Subash Kharel', 111111111)
INSERT INTO Customers (NAME, PHONE) VALUES ('Pradip Acharya', 2222223232)
INSERT INTO Customers (NAME, PHONE) VALUES ('Monica Sharma', 23432122321)
INSERT INTO Customers (NAME, PHONE) VALUES ('Suraj Rimal', 1122112211)
INSERT INTO Customers (NAME, PHONE) VALUES ('Sudip Ghimire', 1122112222)
INSERT INTO Customers (NAME, PHONE) VALUES ('Shree Krishna Tripathi', 3322332233)
INSERT INTO Customers (NAME, PHONE) VALUES ('Sudip Baral', 4433223344)


--INSERT ITEMS
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Whole Chicken', 5, 'Fresh chicken directly transported from Chicago.')
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Spinach', 10, 'Brought from Farmer''s marker.')
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Bread', 8, 'Whole Wheat and Fibrous bread from the local bakery.')
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Milk', 3, 'Whole Milk as well as Non Fat milk.')
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Pizza', 13, 'Hot pizza directly from Primo''s')
INSERT INTO Items (ITEMNAME, PRICE, DESCRIPTION) VALUES ('Mask', 10, 'N95 mask that can prevent COVID infection.')


--INSERT ORDERS
INSERT INTO Orders(CUSTOMERID) VALUES (1)
INSERT INTO Orders(CUSTOMERID) VALUES (1)
INSERT INTO Orders(CUSTOMERID) VALUES (2)
INSERT INTO Orders(CUSTOMERID) VALUES (3)
INSERT INTO Orders(CUSTOMERID) VALUES (4)
INSERT INTO Orders(CUSTOMERID) VALUES (6)


--INSERT ORDERITEMS
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (1, 1, 5)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (2, 3, 8)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (1, 5, 13)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (5, 4, 12)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (3, 2, 8)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (4, 2, 4)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (5, 2, 10)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (2, 2, 5)
INSERT INTO OrderItems(ORDERID, ITEMID, QUANTITY) VALUES (1, 2, 7)
